version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile # Your existing Angular Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

  cypress-tests:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - angular-app
    environment:
      - CYPRESS_baseUrl=http://angular-app:4200
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
